# Generated by Django 4.2.9 on 2024-02-21 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site', models.CharField(max_length=16, unique=True, verbose_name='站点')),
                ('nickname', models.CharField(default=' ', max_length=16, verbose_name='站点昵称')),
                ('sort_id', models.IntegerField(default=1, verbose_name='排序')),
                ('mail', models.IntegerField(default=0, verbose_name='短消息')),
                ('notice', models.IntegerField(default=0, verbose_name='公告')),
                ('user_id', models.CharField(help_text='请填写<font color="orangered">数字UID</font>，<font color="orange">* az,cz,ez,莫妮卡、普斯特等请填写用户名</font>', max_length=16, verbose_name='用户ID')),
                ('passkey', models.CharField(blank=True, max_length=128, null=True, verbose_name='PassKey')),
                ('cookie', models.TextField(help_text='与UA搭配使用效果更佳，请和UA在同一浏览器提取', verbose_name='COOKIE')),
                ('user_agent', models.TextField(default='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0', help_text='请填写你获取cookie的浏览器的User-Agent', verbose_name='User-Agent')),
                ('rss', models.URLField(blank=True, help_text='RSS链接', null=True, verbose_name='RSS地址')),
                ('torrents', models.CharField(blank=True, help_text='免费种子链接', max_length=512, null=True, verbose_name='种子地址')),
                ('sign_in', models.BooleanField(default=True, help_text='是否开启签到', verbose_name='开启签到')),
                ('get_info', models.BooleanField(default=True, help_text='是否抓取站点数据', verbose_name='抓取信息')),
                ('repeat_torrents', models.BooleanField(default=False, verbose_name='辅种支持')),
                ('brush_free', models.BooleanField(default=True, verbose_name='Free刷流')),
                ('brush_rss', models.BooleanField(default=False, help_text='硬刚刷流', verbose_name='RSS刷流')),
                ('package_file', models.BooleanField(default=False, help_text='拆包刷流，只下载一部分，针对大包小硬盘', verbose_name='拆包刷流')),
                ('hr_discern', models.BooleanField(default=False, help_text='是否下载HR种子', verbose_name='开启HR下载')),
                ('search_torrents', models.BooleanField(default=True, help_text='是否开启搜索', verbose_name='开启搜索')),
                ('proxy', models.URLField(blank=True, help_text='部分站点需要', null=True, verbose_name='代理服务器')),
                ('remove_torrent_rules', models.TextField(blank=True, help_text='详细内容请查看文档', null=True, verbose_name='刷流删种')),
                ('mirror', models.URLField(blank=True, null=True, verbose_name='CDN网址')),
                ('time_join', models.DateTimeField(default=datetime.datetime(2024, 2, 1, 0, 0), help_text='请务必填写此项！', verbose_name='注册时间')),
                ('sign_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='签到信息')),
                ('status', models.JSONField(blank=True, default=dict, null=True, verbose_name='站点数据')),
            ],
            options={
                'verbose_name': '我的站点',
                'verbose_name_plural': '我的站点',
            },
        ),
    ]
