url = [ "https://hdcity.city/",]
name = "HD城市"
nickname = "hdcity"
logo = "https://hdcity.city/favicon.ico"
tracker = "sync.leniter.org"
sp_full = 140
limit_speed = 100
tags = "影视"
iyuu = 17
sign_in = 1
get_info = 1
repeat_torrents = 1
brush_free = 1
brush_rss = 1
hr_discern = 0
search_torrents = 1
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "sign"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download?id={}&cuhash={}"
page_user = "userdetails?id={}"
page_search = "pt?incldead=1&spstate=0&inclbookmarked=0&iwannaseethis={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//h1/text()"
sign_info_content = "//h1/following-sibling::p/text()"
hr = 0
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[@href=\"invite\"]/text()[1]"
my_time_join_rule = "//b[text()=\"加入日期\"]/following-sibling::text()[1]"
my_latest_active_rule = "//b[text()=\"最近动向\"]/following-sibling::text()[1]"
my_uploaded_rule = "//a[@href=\"userdetails\"]/i[@title=\"上传量：\"]/following-sibling::text()[1]"
my_downloaded_rule = "//a[@href=\"userdetails\"]/i[@title=\"下载量：\"]/following-sibling::text()[1]"
my_ratio_rule = "//a[@href=\"userdetails\"]/i[@title=\"分享率：\"]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href=\"mybonus\"]/text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),\"每小时能获取\")]/text()[1]"
my_score_rule = "//tr[115]/td[2]/text()"
my_level_rule = "//div[@id=\"bottomnav\"]/div/a/strong/following-sibling::text()[1]"
my_passkey_rule = "//span[@id=\"kpkey\"]/em/text()"
my_uid_rule = "//b[text()=\"ID\"]/following-sibling::text()[1]"
my_hr_rule = "//a[@href=\"myhr.php\"]/text()"
my_leech_rule = "//a[@href=\"userdetails\"]/span[@title=\"当前下载\"]/text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//a[@href=\"userdetails\"]/span[@title=\"当前做种\"]/text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//li/a/i[@id=\"rmsg\"]/following::text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//div[@class=\"block\"][1]/div[@class=\"blocktitle\"]/a"
my_notice_content = "//div[@class=\"block\"][1]/div[@class=\"blocktitle\"]/following-sibling::div"
torrents_rule = "//center/div/div/div[contains(@class,\"trblock\")]"
torrent_title_rule = "./div[@class=\"trm\"]/div/div[@class=\"trbi\"]/a/span/text()"
torrent_subtitle_rule = ".//a[contains(@href,\"detail\")]/parent::td/text()[last()]"
torrent_detail_url_rule = "./div[@class=\"trtop\"]/a/@href"
torrent_category_rule = "./div/div[@class=\"trti\"]/a/span/text()"
torrent_poster_rule = "./div[@class=\"trm\"]/div/div/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,\"download?id=\")]/@href"
torrent_size_rule = ".//div[@class=\"trl\"]/i/following-sibling::text()[1]"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//img[contains(@class,\"pro_\")]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,\"free\")]/following-sibling::font/span/@title"
torrent_release_rule = ".//div[@class=\"trtop\"]/div/text()"
torrent_seeders_rule = ".//a[contains(@href,\"dllist=1#seeders\")]/font/text()"
torrent_leechers_rule = ".//a[contains(@href,\"dllist=1#leechers\")]/text()"
torrent_completers_rule = ".//a[contains(@href,\"viewsnatches?id=\")]/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = 1
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = 0
