url = [ "https://totheglory.im/",]
name = "TTG"
nickname = "ttg"
logo = "https://totheglory.im/favicon.ico"
tracker = "tracker.totheglory.im"
sp_full = 107
limit_speed = 30
tags = "影视"
iyuu = 14
sign_in = 1
get_info = 1
repeat_torrents = 1
brush_free = 1
brush_rss = 1
hr_discern = 0
search_torrents = 1
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "signed.php"
page_control_panel = "usercp.php"
page_detail = "t/{}/"
page_download = "dl/{}/{}"
page_user = "userdetails.php?id={}"
page_search = "browse.php?search_field={}&c=M"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "userdetails.php?id={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/table//td//text()"
hr = 0
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,\"invite.php\")]/span/text()[1]"
my_time_join_rule = "//td[contains(text(),\"注册日期\")]/following-sibling::td[1]/text()"
my_latest_active_rule = "//td[contains(text(),\"上次访问\")]/following-sibling::td[1]/text()"
my_uploaded_rule = "//font[contains(text(),\"上传量\")]/following-sibling::font[1]/a/text()[1]"
my_downloaded_rule = "//font[contains(text(),\"下载量\")]/following-sibling::font[1]/a/text()[1]"
my_ratio_rule = "//font[contains(text(),\"分享率 \")][1]/following-sibling::font[1]/text()[1]"
my_bonus_rule = "//a[contains(@href,\"mybonus.php\")]/text()[1]"
my_per_hour_bonus_rule = "//td[contains(text(),\"总计\")]/following-sibling::td/text()"
my_score_rule = "//font[contains(text(),\"HP\")]/following-sibling::text()[1]"
my_level_rule = "//td[contains(text(),\"等级\")]/following-sibling::td/text()"
my_passkey_rule = "//td[contains(text(),\"Passkey\")]/following-sibling::td[1]/text()"
my_uid_rule = "//a[contains(@href,\"/userdetails.php?id=\")]/@href"
my_hr_rule = "//a[@href=\"myhr.php\"]/text()"
my_leech_rule = "//img[contains(@title,\"下载中\")]/following-sibling::font[1]/span/text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[contains(@title,\"做种中\")]/following-sibling::font[1]/span/text()[1]"
my_seed_vol_rule = "//*[@id=\"ka2\"]//td[not(@class)][4]"
my_mailbox_rule = "//a[contains(@href,\"messages.php\")]/font[contains(text(),\"个\")]/text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"/announcement.php\"]/font/text()"
my_notice_title = "//td[@class=\"text\"]/ul/li"
my_notice_content = "//td[@class=\"text\"]/div/a/following-sibling::div"
torrents_rule = "//table[@id=\"torrent_table\"]/tr[@class]"
torrent_title_rule = ".//div[@class=\"name_left\"]/a/b//text()[1][name(..)!=\"span\"]"
torrent_subtitle_rule = ".//div[@class=\"name_left\"]/a/b//span/text()"
torrent_detail_url_rule = ".//div/a[contains(@href,\"/t/\")]/@href"
torrent_category_rule = ".//img[contains(@src,\"cate\")]/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//img[contains(@class,\"dl_img\")]/parent::a/@href"
torrent_size_rule = ".//td[7]/text()"
torrent_hr_rule = ".//img[@title=\"Hit and Run\"]"
torrent_sale_rule = ".//img[contains(@src,\"/pic/ico_\")]/@alt"
torrent_sale_expire_rule = ".//span/@onclick"
torrent_release_rule = ".//td[5]//text()"
torrent_seeders_rule = ".//a[contains(@href,\"&toseeders\")]//text()"
torrent_leechers_rule = ".//a[contains(@href,\"&todlers\")]//text()"
torrent_completers_rule = ".//td[8]/text()[1]"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = 1
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = 0
