url = [ "https://u2.dmhy.org/",]
name = "U2"
nickname = "demy"
logo = "https://u2.dmhy.org/favicon.ico"
tracker = "dmhy.best"
sp_full = 200
limit_speed = 50
tags = "影视"
iyuu = 37
sign_in = 1
get_info = 1
repeat_torrents = 1
brush_free = 1
brush_rss = 1
hr_discern = 0
search_torrents = 1
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "showup.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mprecent.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/table//td//text()"
hr = 0
hr_rate = 2
hr_time = 10
my_invitation_rule = "//span/a[contains(@href,\"invite.php?id=\")]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),\"加入\")]/following-sibling::td/time/text()"
my_latest_active_rule = "//td[contains(text(),\"最近动向\")]/following-sibling::td/time/text()"
my_uploaded_rule = "//span[@class=\"color_uploaded\"]/following-sibling::text()[1]"
my_downloaded_rule = "//span[@class=\"color_downloaded\"]/following-sibling::text()[1]"
my_ratio_rule = "//span[contains(text(),\"分享率\")][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href=\"ucoin.php\"]/following-sibling::span[1]//text()"
my_per_hour_bonus_rule = "//td[@id=\"outer\"]//td[@class=\"text\"]/text()"
my_score_rule = "//font[@class=\"color_bonus\" and contains(text(),\"积分\")]/following-sibling::text()[1]"
my_level_rule = "//span/span/a[contains(@href, \"userdetails.php?id=\")]/@class"
my_passkey_rule = "//td[contains(text(),\"密钥\")]/following-sibling::td[1]/span/@data-content"
my_uid_rule = "//span/span/a[contains(@href, \"userdetails.php?id=\")]/@href"
my_hr_rule = "//a[@href=\"myhr.php\"]/text()"
my_leech_rule = "//img[@class=\"arrowdown\"][1]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//a[contains(@href,\"#seedlist\")]//text()"
my_seed_vol_rule = "//table/preceding-sibling::br/preceding-sibling::text()[1]"
my_mailbox_rule = "//a[@href=\"messages.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//td[@class=\"text\"]/div/a"
my_notice_content = "//td[@class=\"text\"]/div/a/following-sibling::div"
torrents_rule = "//table[@class=\"torrents\"]/tbody/tr/td[@class!=\"colhead\"]/parent::tr"
torrent_title_rule = ".//a[contains(@href,\"detail\")]/parent::td/a/text()"
torrent_subtitle_rule = ".//td/span/text()"
torrent_detail_url_rule = ".//a[contains(@href,\"detail\")]/parent::td/a/@href"
torrent_category_rule = ".//td[1]/a[contains(@href, \"?cat=\")]/text()[2]"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,\"download\")]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//img[contains(@class,\"pro_\")]/@alt"
torrent_sale_expire_rule = ".//b/time/@title"
torrent_release_rule = ".//td[4]/time/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\" 种子散列值:\")]/following-sibling::text()[1]"
detail_free_rule = "//td[contains(text(), \" 流量优惠\")]/following-sibling::td/img[starts-with(@class, \"pro_\")]/@alt"
detail_free_expire_rule = "//td[contains(text(), \" 流量优惠\")]/following-sibling::td/b/time/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//td[1]/a[contains(@href, \"?cat=\")]/text()[1]"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = 1
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = 0
