url = [ "https://www.pttime.top/",]
name = "时间"
nickname = "pttime"
logo = "https://www.pttime.top/favicon.ico"
tracker = "www.pttime.top"
sp_full = 150
limit_speed = 95
tags = "影视"
iyuu = 60
sign_in = 1
get_info = 1
repeat_torrents = 1
brush_free = 1
brush_rss = 1
hr_discern = 0
search_torrents = 1
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlist.php?type=seeding&userid={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id="
sign_info_title = "//td[1]/b[1]/text()"
sign_info_content = "//td[1]/font[1]/text()"
hr = 0
hr_rate = 2
hr_time = 10
my_invitation_rule = "//td[contains(text(),\"剩余邀请量\")]/following::a[contains(@href,\"invite.php\")][1]//text()[1]"
my_time_join_rule = "//td[contains(text(),\"加入\")]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),\"最近\")]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//font[@class=\"color_uploaded\"]/following-sibling::text()"
my_downloaded_rule = "//font[@class=\"color_downloaded\"]/following-sibling::text()"
my_ratio_rule = "//font[@class=\"color_ratio\"]/following-sibling::text()"
my_bonus_rule = "//a[@href=\"mybonus.php\"]/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),\"每小时\")]/text()[1]"
my_score_rule = "//font[@class=\"color_bonus\" and contains(text(),\"积分\")]/following-sibling::text()[1]"
my_level_rule = "//*[@id=\"info_block\"]//tr[1]/td/span/a[1]/@class"
my_passkey_rule = "//td[contains(text(),\"秘钥\")]/following-sibling::td[1]/span/text()"
my_uid_rule = "//a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@href"
my_hr_rule = "//a[@href=\"myhr.php\"]//text()"
my_leech_rule = "//i[@title=\"当前下载\"]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//i[@title=\"当前做种\"]/following-sibling::text()[1]"
my_seed_vol_rule = "//b[contains(text(),\"资源总大小：\")]/following-sibling::text()[1]"
my_mailbox_rule = "//a[@href=\"messages.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::div/following-sibling::a[1]/div/text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//td[@class=\"text\"]/div/a"
my_notice_content = "//td[@class=\"text\"]/div/a/following-sibling::div"
torrents_rule = "//table[@class=\"torrents\"]/tr"
torrent_title_rule = ".//tr/td[@class=\"embedded\"][1]/text()"
torrent_subtitle_rule = ".//a[contains(@href,\"detail\")]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class=\"embedded\"]/a[contains(@href,\"detail\")]/b/parent::a/@href"
torrent_category_rule = ".//td[@class=\"rowfollow nowrap\"][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,\"download\")]/@href"
torrent_size_rule = ".//td[6]/text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//font[contains(@class,\"free\")]/text()"
torrent_sale_expire_rule = ".//font[contains(@class,\"free\")]/following-sibling::span[1]/@title"
torrent_release_rule = ".//td[@class=\"rowfollow nowrap\"]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,\"#seeders\")]//text()"
torrent_leechers_rule = ".//a[contains(@href,\"#leechers\")]//text()"
torrent_completers_rule = ".//a[contains(@href,\"viewsnatches\")]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = 1
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = 0
