url = [ "https://greatposterwall.com/",]
name = "海豹GPW"
nickname = "gpw"
logo = "https://greatposterwall.com/favicon.ico"
tracker = "greatposterwall.com"
sp_full = 0
limit_speed = 100
tags = "影视"
iyuu = 64
sign_in = 0
get_info = 1
repeat_torrents = 1
brush_free = 0
brush_rss = 0
hr_discern = 0
search_torrents = 1
page_index = "index.php"
page_torrents = "torrents.php"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "torrents.php?action=download&id={}"
page_user = "ajax.php?action=user&id={}"
page_search = "torrents.php?searchstr={}"
page_message = "inbox.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "bonus.php?action=bprates"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "bonus.php?action=bprates"
page_completed = "bonus.php?action=bprates"
page_mybonus = "ajax.php?action=index"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/table//td//text()"
hr = 0
hr_rate = 2
hr_time = 10
my_invitation_rule = "//span[text()=\"邀请数量: \"]/following-sibling::text()[1]"
my_time_join_rule = "//li[@ id=\"join-date-value\"]/@data-value"
my_latest_active_rule = "//li[@ id=\"last-access-date-value\"]/@data-value"
my_uploaded_rule = "//li[@ id=\"uploaded-value\"]/@data-value"
my_downloaded_rule = "//li[@ id=\"downloaded-value\"]/@data-value"
my_ratio_rule = "//li[@ id=\"ratio-value\"]/@data-value"
my_bonus_rule = "//li[@ id=\"bp-value\"]/@data-value"
my_per_hour_bonus_rule = "//li[@ id=\"bp-rate-value\"]/@data-value"
my_score_rule = "//tr[115]/td[2]/text()"
my_level_rule = "//li[@ id=\"class-value\"]/@data-value"
my_passkey_rule = "//td[contains(text(),\"密钥\")]/following-sibling::td[1]/text()"
my_uid_rule = "//div[@class=\"HeaderProfile\"]/a[contains(@href,\"user.php?id=\")]/@href"
my_hr_rule = "//a[@href=\"myhr.php\"]/text()"
my_leech_rule = "//table[@id=\"torrent_table\"]/tbody/tr"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//td[@id=\"seeding-count-value\"]/@data-value"
my_seed_vol_rule = "//td[@id=\"seeding-size-value\"]/@data-value"
my_mailbox_rule = "//a[@href=\"messages.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//td[@class=\"text\"]/div/a"
my_notice_content = "//td[@class=\"text\"]/div/a/following-sibling::div"
torrents_rule = "//tr[contains(@class,\"TableTorrent-rowTitle Table-row torrent_checked \")]"
torrent_title_rule = "./td/div/a/@data-tooltip"
torrent_subtitle_rule = "./td/div/a/@data-tooltip"
torrent_detail_url_rule = "./td/div/a/span/span[contains(@class,\"TorrentTitle-item \")]/text()"
torrent_category_rule = ".//td[@class=\"rowfollow nowrap\"]/a/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = "./td/div/span/a/@href"
torrent_size_rule = "./td[contains(@class,\"TableTorrent-cellStatSize\")]/text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = "./td/div/a/span/span[contains(@class,\"free \")]/text()"
torrent_sale_expire_rule = "./td/div/a/span/span[contains(@class,\"free \")]/@data-tooltip"
torrent_release_rule = "./td/span/@data-tooltip"
torrent_seeders_rule = "./td[contains(@class,\"TableTorrent-cellStatSeeders\")]/text()"
torrent_leechers_rule = "./td[contains(@class,\"TableTorrent-cellStatLeechers\")]/text()"
torrent_completers_rule = "./td[contains(@class,\"TableTorrent-cellStatSnatches\")]/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = "//td/div/a/span/span[contains(@class,\"TorrentTitle-item \")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = 1
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = 0
