url = [ "https://hdchina.org/",]
name = "瓷器"
nickname = "hdchina"
logo = "https://hdchina.org/favicon.ico"
tracker = "tracker.hdchina.org"
sp_full = 70
limit_speed = 95
tags = "影视"
iyuu = 28
sign_in = 1
get_info = 1
repeat_torrents = 1
brush_free = 1
brush_rss = 1
hr_discern = 0
search_torrents = 1
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "plugin_sign-in.php?cmd=signin"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}&hit=1"
page_download = "download.php?id={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "ajax_getusertorrentlist.php"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/table//td//text()"
hr = 0
hr_rate = 2
hr_time = 10
my_invitation_rule = "//p/a[contains(@href,\"invite.php?id=\")]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),\"加入\")]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[text()=\" 最近动向\"]/following-sibling::td/span/@title[1]"
my_uploaded_rule = "//strong[contains(text(),\"上传量\")]/following-sibling::text()"
my_downloaded_rule = "//strong[contains(text(),\"下载量\")]/following-sibling::text()"
my_ratio_rule = "//strong[contains(text(),\"分享率\")]/following-sibling::font[1]/text()"
my_bonus_rule = "//a[contains(@href,\"mybonus.php\")]/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div/h3[contains(text(),\"每小时\")]/text()[1]"
my_score_rule = "//font[@class=\"color_bonus\" and contains(text(),\"积分\")]/following-sibling::text()[1]"
my_level_rule = "//p/span/a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@class"
my_passkey_rule = "//td[contains(text(),\"密钥\")]/following-sibling::td[1]/text()"
my_uid_rule = "//p/span/a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@href"
my_hr_rule = "//a[@href=\"myhr.php\"]//text()"
my_leech_rule = "//i[@title=\"当前下载\"][1]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//i[@title=\"当前做种\"][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href=\"messages.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//div[@class=\"announcebox\"]/div/h4"
my_notice_content = "//div[@class=\"announcebox\"]/div/h4/following-sibling::h3"
torrents_rule = "//table[@class=\"torrent_list\"]/tr[not(contains(@class, \"tab_header\"))]"
torrent_title_rule = ".//h3/a[contains(@href,\"details.php\")]/text()"
torrent_subtitle_rule = ".//h4/text()"
torrent_detail_url_rule = ".//h3/a[contains(@href,\"details.php\")]/@href"
torrent_category_rule = ".//td[1]/a/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,\"download.php?hash\")]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//img[contains(@class,\"pro_\")]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,\"free\")]/../following-sibling::span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,\"#seeders\")]/text()"
torrent_leechers_rule = ".//a[contains(@href,\"#leechers\")]/text()"
torrent_completers_rule = ".//a[contains(@href,\"viewsnatches\")]//text()"
detail_title_rule = "//div[@class=\"m_name\"]/h2/text()[1]"
detail_subtitle_rule = "//div[@class=\"m_name\"]/h3/text()[1]"
detail_download_url_rule = "//a[contains(@href,\"download.php?hash\") and @title=\"下载种子\"]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = ".//img[contains(@class,\"pro_\")]/@alt"
detail_free_expire_rule = ".//img[contains(@class,\"pro_\")]/@onmouseover"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//text()[contains(.,\"◎IMDb 链接\")]/following-sibling::a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@hr"
detail_poster_rule = "//td/div[@class=\"imgbox\"]/img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = 1
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = 0
